### PR TITLE
Add Gatsby React Version

### PR DESCRIPTION
**Pull request by kpfromer**
## What this PR does / why we need it

This PR will replace the old codebase with the React version of it. The reason to use React is that it allows for a much more dynamic website that would be hard to achieve without using JavaScript. For example, the new calendar design was made easier with [React](https://reactjs.org/). React also allows us to create components that can be reused.
[Gatsby](https://www.gatsbyjs.org/) utilizes React but adds a few features. Gatsby compiles as much as it can on build to increase website loading speeds (it is a static website creator). It will [optimize images](https://www.gatsbyjs.org/packages/gatsby-image/#problem) automatically and there are a ton of [useful plugins](https://www.gatsbyjs.org/plugins/). Also, Gatsby has a lot of [support](https://www.gatsbyjs.org/showcase/).

## Related Issues

None.

## Some questions

- [x] I have read the contributing guidelines
- [x] I abide by this repository Code of Conduct

## Special notes for your reviewer

- Does the GitHub look good? 
- We might need to create a token for HackCU for the GitHub action to work properly. 
- Does the CNAME look good as well?

## Additional Notes

Maybe we could update the site to use [Preact](https://preactjs.com/) instead of React for [reduced bundle size](https://henrique.codes/speed-up-gatsby-site/).

### CODE REVIEW

**Comment by kpfromer** [comment]
Also the mentors link needs to be removed, content updated for HackCU VI and new colors need to be added to theme file.

**Comment by peasant98** [comment]
A couple of things:

does the schedule work for both saturday and sunday?

It seems that some of the logos appear big when the site is initially being loaded.

**Comment by kpfromer** [comment]
The problem with the large icons should be fixed now (I would still test, but it worked for me).

**Comment by peasant98** [comment]
yep, worked for me as well.

**Comment by peasant98** [comment]
Can you add some steps to the `README.md` file as well?

**Comment by kpfromer** [comment]
Yeah, I will do that tomorrow.

**Review by peasant98 — APPROVED** [review]

**Pull request merged**
