### PR TITLE
Use rebass for site styling

### PR DESCRIPTION
**Pull request by kpfromer**
## What this PR does / why we need it

**This is a WIP**

The website will remove the need for materialize and will use [rebass](https://rebassjs.org/) for simple components (that function well). This makes the site more customizable and easier to develop for. I also worked on making the schedule more responsive and the coder for it simpler (it was a serious mess before). 

_BTW, we can easily add [dark mode](https://theme-ui.com/color-modes/) and other themes with [theme UI](https://theme-ui.com/) and rebass 😊_

## Some questions

- [x] I have read the contributing guidelines
- [x] I abide by this repository Code of Conduct
- [x] Does the schedule/layout look good on mobile? (Should I go back to the old list style?)

### CODE REVIEW

**Comment by lucca** [comment]
this looks good so far! i can't see the schedule bc it doesn't load, but the events/prizes seem fine on mobile. it's nice that they're more compact so you don't have to scroll as much
one thing i would change is the font size for the workshop names, something like h3 instead of h5 seems better just so it's more immediately noticeable than anything else in the block
and dark theme 👀

**Comment by peasant98** [comment]
lgtm, I think it would be nice to see the text a bit more spaced out (mainly regarding the main page at https://deploy-preview-30--lucid-knuth-ff6d5d.netlify.com/)

**Comment by kpfromer** [comment]
Tell me what you think, with the changes. I think the dark mode could use better colors.

**Comment by peasant98** [comment]
lgtm

**Review by peasant98 — APPROVED** [review]
yep!

**Comment by lucca** [comment]
> Tell me what you think, with the changes. I think the dark mode could use better colors.

I think ideally all of the text should be white and we have two tones of dark to differentiate background / cards. I'll probably play around with it tmrw but I really like twitter's dark theme as a starting point

**Comment by SatishUpadhyaya** [comment]
lgtm

**Pull request merged**
